//! Embed every `plugins/*.toml` at compile time — no manual manifest list.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    let plugins_dir = manifest_dir.join("../../plugins");
    println!("cargo:rerun-if-changed={}", plugins_dir.display());

    let mut stems: Vec<String> = Vec::new();
    for entry in fs::read_dir(&plugins_dir).expect("plugins/ directory missing") {
        let path = entry.expect("read plugins dir").path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .expect("plugin filename")
            .to_string();
        println!("cargo:rerun-if-changed={}", path.display());
        stems.push(stem);
    }
    stems.sort();

    let out = manifest_dir.join("src/builtin_plugins.rs");
    let mut body = String::from(
        "//! Built-in plugins embedded at compile time from `plugins/*.toml`.\n\
         //! Generated by `build.rs` — do not edit by hand.\n\n\
         /// `(stem, toml contents)` for every shipped plugin file.\n\
         pub fn builtin_sources() -> &'static [(&'static str, &'static str)] {\n\
         \t&[\n",
    );
    for stem in &stems {
        body.push_str(&format!(
            "\t\t(\"{stem}\", include_str!(\"../../../plugins/{stem}.toml\")),\n"
        ));
    }
    body.push_str("\t]\n}\n");
    fs::write(out, body).expect("write builtin_plugins.rs");
}
